name: faker_korean
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/Oh-Kang94/faker_korean

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
